# configs/data.yaml

input_len: 14
horizon: 7
stride: 2

source_domain: java
target_domain: papua

target_col: max_temperature

feature_cols:
  - max_temperature
  - latitude
  - longitude
  - elevation
  - sin_doy
  - cos_doy
  - solar_declination
  - dmi east
  - nino anom 3.4

local_temporal_cols:
  - max_temperature
  - sin_doy
  - cos_doy
  - solar_declination

geo_cols:
  - latitude
  - longitude
  - elevation

climate_cols:
  - nino anom 3.4
  - dmi east