epochs: 100
batch_size: 256
lr: 0.001

n_repeats: 10

low_resources_fracs: 
  - 0.05
  - 0.15
  - 0.25

methods:
  - arima
  - vtt
  - vtkm
  - attf
  - daf 
  - tft
  - tft da

device: cuda

use_early_stop: false
use_amp: true
use_compile: false

